#!/bin/bash

sudo docker run -it --rm \
    --network p_net \
    -v /home/leatep/code/Vaava:/Va \
    -e vaava=/Va \
    -e PSQL_HOST=postgres \
    -e PSQL_USER=postgres \
    -e PSQL_DB=sql \
    -e PGPASSWORD=123 \
    psql_python /Va/mining.py